In [49]:
from sklearn.datasets import load_iris

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
iris = load_iris()

In [53]:
X = iris.data
y = iris.target

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [55]:
clf = RandomForestClassifier()

In [56]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [57]:
clf.predict(X_test)

array([1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1,
       2, 1, 0, 0, 1, 1, 2, 0])

In [58]:
from sklearn.metrics import accuracy_score

In [59]:
y_pred = clf.predict(X_test)

In [60]:
accuracy = accuracy_score(y_test, y_pred)

In [61]:
print(accuracy)

0.9333333333333333


In [62]:
print(X_test[:5], y_test[:5])

[[5.7 2.9 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.5 4.2 1.4 0.2]
 [6.3 2.3 4.4 1.3]
 [4.4 3.  1.3 0.2]] [1 0 0 1 0]


In [63]:
import numpy as np

print("List of all labels to classify:", iris.target_names)
sample_data = np.array([[5.1, 3.5, 1.4, 0.2]])
predicted_class = clf.predict(sample_data)
print(f"Predicted class for sample data: {iris.target_names[predicted_class][0]}")

List of all labels to classify: ['setosa' 'versicolor' 'virginica']
Predicted class for sample data: setosa
