In [1]:
!pip install keras_nlp
!pip install tensorflow
!pip install tensorflow_datasets
!pip install tensorflow-text
!pip install keras

In [2]:
import keras
import keras_nlp
import tensorflow_datasets
import keras
from keras_nlp.models import AlbertTokenizer, AlbertPreprocessor

Using TensorFlow backend


In [3]:
tokenizer = AlbertTokenizer.from_preset("albert_base_en_uncased",)

In [4]:
tokenizer.tokenize(["Goat is good", "Sheep is good"])

<tf.RaggedTensor [[13, 1, 111, 721, 25, 254],
 [13, 1, 438, 3492, 25, 254]]>

In [5]:
import io

In [6]:
bytes_io = io.BytesIO()

In [7]:
!pip install tensorflow

In [8]:
import tensorflow as tf


In [9]:
ds = tf.data.Dataset.from_tensor_slices(["The goat was huge"])

In [10]:
!pip install sentencepiece

In [11]:
import sentencepiece as spm

In [12]:
spm.SentencePieceTrainer.train(
    sentence_iterator=ds.as_numpy_iterator(),
    model_writer = bytes_io,
    vocab_size=9,
    model_type="WORD",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3,
    pad_piece="<pad>",
    unk_piece="<unk>",
    bos_piece="[CLS]",
    eos_piece="[SEP]",
    user_defined_symbols="[MASK]",
)

In [13]:
tokenizer = AlbertTokenizer(proto=bytes_io.getvalue())

In [14]:
tokenizer("The goat is a masterpiece")

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 1], dtype=int32)>

In [15]:
preprocessor = AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [16]:
preprocessor("What a game!")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([   2,   13,    1, 6775,   21,  250,  187,    3,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,   

In [17]:
preprocessor("The quick fox jumped")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([   2,   13,    1,  438, 2231, 2385, 4298,    3,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,   

In [18]:
preprocessor(["Is the goat good?", "Is the cow big?"])

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [19]:
preprocessor(["What a cow?", "Is that a rabbit?", "Is this a tiger?"])

{'token_ids': <tf.Tensor: shape=(3, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(3, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(3, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [20]:
preprocessor = AlbertPreprocessor(tokenizer)

In [21]:
preprocessor("The goat is a masterpiece")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([2, 5, 6, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
bytes_io = io.BytesIO()

In [23]:
ds = tf.data.Dataset.from_tensor_slices(["The story is interesting"])

In [24]:
spm.SentencePieceTrainer.train(
    sentence_iterator = ds.as_numpy_iterator(),
    model_writer= bytes_io,
    vocab_size=9,
    model_type="WORD",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3,
    pad_piece="<pad>",
    unk_piece="<unk>",
    bos_piece="[CLS]",
    eos_piece="[SEP]",
    user_defined_symbols="[MASK]"
)

In [25]:
tokenizer = AlbertTokenizer(proto=bytes_io.getvalue(),)

In [26]:
preprocessor = AlbertPreprocessor(tokenizer)

In [27]:
preprocessor("The story is interesting")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([2, 5, 8, 7, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
first = tf.constant(["The story is interesting", "the story is a mystery"])

In [29]:
second = tf.constant(["The story looks interesting and cool", "Is that a phone?"])

In [30]:
label = tf.constant([1, 1])

In [31]:
#Map labeled single sentence
ds = tf.data.Dataset.from_tensor_slices((first, label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [32]:
#map unlabeled single sentences
ds = tf.data.Dataset.from_tensor_slices(first)
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [33]:
#map labeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices(((first, second), label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [34]:
#map unlabled sentence pairs
ds = tf.data.Dataset.from_tensor_slices((first, second))

In [35]:
ds = ds.map(lambda first, second: preprocessor(x=(first, second)), num_parallel_calls=tf.data.AUTOTUNE)

In [36]:
ds

<_ParallelMapDataset element_spec={'token_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'segment_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'padding_mask': TensorSpec(shape=(512,), dtype=tf.bool, name=None)}>

In [37]:
third = tf.constant(["The game was well played", "The game was interesting, isn't it?"])
fourth = tf.constant(["The fox is quick", "The tiger is too quick"])

In [38]:
label = tf.constant([1, 1])

In [39]:
#map labeled single sentences
ds = tf.data.Dataset.from_tensor_slices((third, fourth))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [40]:
#map unlabeled single sentences
ds = tf.data.Dataset.from_tensor_slices(third)
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [42]:
#map labeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices(((third, fourth), label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [43]:
#map unlabeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices((third, fourth))

In [44]:
ds = ds.map(
    lambda third, fourth:preprocessor(x=(third, fourth)),
    num_parallel_calls=tf.data.AUTOTUNE
)

In [45]:
ds

<_ParallelMapDataset element_spec={'token_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'segment_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'padding_mask': TensorSpec(shape=(512,), dtype=tf.bool, name=None)}>

In [46]:
from keras_nlp.models import AlbertBackbone

In [49]:
import numpy as np


In [50]:
input_data = {
    "token_ids": np.ones(shape=(1, 12), dtype="int32"),
    "segment_ids": np.array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0]]),
    "padding_mask": np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

In [51]:
model = AlbertBackbone(
    vocabulary_size=30000,
    num_layers=12,
    num_heads=12,
    num_groups=1,
    num_inner_repetitions=1,
    embedding_dim=128,
    hidden_dim=768,
    intermediate_dim=3072,
    max_sequence_length=12,
)

In [52]:
output = model(input_data)

In [53]:
output

{'sequence_output': <tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
 array([[[ 1.4808228 , -0.06938782,  0.7234533 , ...,  0.4026623 ,
          -2.302642  , -1.2570531 ],
         [ 1.3868036 ,  0.10428643,  0.68579876, ...,  0.02492731,
          -2.048979  , -0.98513925],
         [ 1.5992649 , -0.30511796,  0.91260016, ..., -0.25022513,
          -1.6114941 , -1.4929962 ],
         ...,
         [ 1.604283  ,  0.9069713 ,  0.96306974, ..., -0.15491767,
          -1.4957494 , -0.6091589 ],
         [ 0.9365893 ,  0.26974607,  0.25793144, ..., -0.6287644 ,
          -2.1779764 , -1.2142931 ],
         [ 1.0742928 , -0.21507901,  0.38710928, ..., -0.24166529,
          -1.9188505 , -0.84623885]]], dtype=float32)>,
 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-1.77859411e-01, -3.22879374e-01, -1.81734622e-01,
         -3.20391208e-01,  6.16850078e-01,  1.66342184e-02,
         -2.42131222e-02,  4.36578661e-01,  7.34589159e-01,
          4.36153740e