In [1]:
!pip install keras_nlp
!pip install tensorflow
!pip install tensorflow_datasets
!pip install tensorflow-text
!pip install keras

In [2]:
import keras
import keras_nlp
import tensorflow_datasets
import keras
from keras_nlp.models import AlbertTokenizer, AlbertPreprocessor

Using TensorFlow backend


In [3]:
tokenizer = AlbertTokenizer.from_preset("albert_base_en_uncased",)

In [4]:
tokenizer.tokenize(["Goat is good", "Sheep is good"])

<tf.RaggedTensor [[13, 1, 111, 721, 25, 254],
 [13, 1, 438, 3492, 25, 254]]>

In [5]:
import io

In [6]:
bytes_io = io.BytesIO()

In [7]:
!pip install tensorflow

In [8]:
import tensorflow as tf


In [9]:
ds = tf.data.Dataset.from_tensor_slices(["The goat was huge"])

In [10]:
!pip install sentencepiece

In [11]:
import sentencepiece as spm

In [12]:
spm.SentencePieceTrainer.train(
    sentence_iterator=ds.as_numpy_iterator(),
    model_writer = bytes_io,
    vocab_size=9,
    model_type="WORD",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3,
    pad_piece="<pad>",
    unk_piece="<unk>",
    bos_piece="[CLS]",
    eos_piece="[SEP]",
    user_defined_symbols="[MASK]",
)

In [13]:
tokenizer = AlbertTokenizer(proto=bytes_io.getvalue())

In [14]:
tokenizer("The goat is a masterpiece")

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 1], dtype=int32)>

In [15]:
preprocessor = AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [16]:
preprocessor("What a game!")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([   2,   13,    1, 6775,   21,  250,  187,    3,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,   

In [17]:
preprocessor("The quick fox jumped")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([   2,   13,    1,  438, 2231, 2385, 4298,    3,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,   

In [18]:
preprocessor(["Is the goat good?", "Is the cow big?"])

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [19]:
preprocessor(["What a cow?", "Is that a rabbit?", "Is this a tiger?"])

{'token_ids': <tf.Tensor: shape=(3, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(3, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(3, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [20]:
preprocessor = AlbertPreprocessor(tokenizer)

In [21]:
preprocessor("The goat is a masterpiece")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([2, 5, 6, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
bytes_io = io.BytesIO()

In [23]:
ds = tf.data.Dataset.from_tensor_slices(["The story is interesting"])

In [24]:
spm.SentencePieceTrainer.train(
    sentence_iterator = ds.as_numpy_iterator(),
    model_writer= bytes_io,
    vocab_size=9,
    model_type="WORD",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3,
    pad_piece="<pad>",
    unk_piece="<unk>",
    bos_piece="[CLS]",
    eos_piece="[SEP]",
    user_defined_symbols="[MASK]"
)

In [25]:
tokenizer = AlbertTokenizer(proto=bytes_io.getvalue(),)

In [26]:
preprocessor = AlbertPreprocessor(tokenizer)

In [27]:
preprocessor("The story is interesting")

{'token_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
 array([2, 5, 8, 7, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
first = tf.constant(["The story is interesting", "the story is a mystery"])

In [29]:
second = tf.constant(["The story looks interesting and cool", "Is that a phone?"])

In [30]:
label = tf.constant([1, 1])

In [31]:
#Map labeled single sentence
ds = tf.data.Dataset.from_tensor_slices((first, label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [32]:
#map unlabeled single sentences
ds = tf.data.Dataset.from_tensor_slices(first)
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [33]:
#map labeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices(((first, second), label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [34]:
#map unlabled sentence pairs
ds = tf.data.Dataset.from_tensor_slices((first, second))

In [35]:
ds = ds.map(lambda first, second: preprocessor(x=(first, second)), num_parallel_calls=tf.data.AUTOTUNE)

In [36]:
ds

<_ParallelMapDataset element_spec={'token_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'segment_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'padding_mask': TensorSpec(shape=(512,), dtype=tf.bool, name=None)}>

In [37]:
third = tf.constant(["The game was well played", "The game was interesting, isn't it?"])
fourth = tf.constant(["The fox is quick", "The tiger is too quick"])

In [38]:
label = tf.constant([1, 1])

In [39]:
#map labeled single sentences
ds = tf.data.Dataset.from_tensor_slices((third, fourth))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [40]:
#map unlabeled single sentences
ds = tf.data.Dataset.from_tensor_slices(third)
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [41]:
#map labeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices(((third, fourth), label))
ds = ds.map(preprocessor, num_parallel_calls=tf.data.AUTOTUNE)

In [42]:
#map unlabeled sentence pairs
ds = tf.data.Dataset.from_tensor_slices((third, fourth))

In [43]:
ds = ds.map(
    lambda third, fourth:preprocessor(x=(third, fourth)),
    num_parallel_calls=tf.data.AUTOTUNE
)

In [44]:
ds

<_ParallelMapDataset element_spec={'token_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'segment_ids': TensorSpec(shape=(512,), dtype=tf.int32, name=None), 'padding_mask': TensorSpec(shape=(512,), dtype=tf.bool, name=None)}>

In [45]:
from keras_nlp.models import AlbertBackbone

In [46]:
import numpy as np


In [47]:
input_data = {
    "token_ids": np.ones(shape=(1, 12), dtype="int32"),
    "segment_ids": np.array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0]]),
    "padding_mask": np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

In [48]:
model = AlbertBackbone(
    vocabulary_size=30000,
    num_layers=12,
    num_heads=12,
    num_groups=1,
    num_inner_repetitions=1,
    embedding_dim=128,
    hidden_dim=768,
    intermediate_dim=3072,
    max_sequence_length=12,
)

In [49]:
output = model(input_data)

In [50]:
output

{'sequence_output': <tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
 array([[[-0.7213105 , -1.6086907 ,  1.0146646 , ..., -0.47958714,
           0.30777895,  0.13305013],
         [-0.3592714 , -2.004273  ,  1.2183511 , ..., -0.76225096,
           0.51566917,  0.5766828 ],
         [-0.5072842 , -2.2241697 ,  1.2947727 , ..., -1.2558162 ,
           0.5181343 ,  0.10891744],
         ...,
         [-0.68403184, -1.765363  ,  0.61937   , ..., -1.0953411 ,
           0.6547122 , -0.40986043],
         [-0.77370816, -1.7514365 ,  0.6784403 , ..., -1.059352  ,
          -0.02456058, -0.10135846],
         [-0.7822539 , -1.5234926 ,  0.81674945, ..., -1.1122056 ,
           0.72969407,  0.0115099 ]]], dtype=float32)>,
 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[-3.72024238e-01,  2.17629150e-01,  3.11642468e-01,
          3.99030447e-01,  3.09600204e-01,  4.59668696e-01,
         -4.66012865e-01,  6.26449510e-02,  2.07674220e-01,
         -1.84977427e

In [51]:
input_data = {
    "token_ids": np.ones(shape=(1, 12), dtype="int32"),
    "segment_ids": np.array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0]]),
    "padding_mask": np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

In [52]:
model = AlbertBackbone(
    vocabulary_size=30000,
    num_layers=12,
    num_heads=12,
    num_groups=1,
    num_inner_repetitions=1,
    embedding_dim=128,
    hidden_dim=768,
    intermediate_dim=3072,
    max_sequence_length=12
)

In [53]:
output = model(input_data)

In [54]:
output

{'sequence_output': <tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
 array([[[-0.13088837,  0.08823976, -1.2268842 , ...,  2.666011  ,
           0.97006965, -0.55991125],
         [-0.04050724, -0.3733532 , -1.0165486 , ...,  2.0815506 ,
           0.7795344 , -0.7208579 ],
         [ 0.52730656, -0.20665151, -1.1171924 , ...,  2.5001056 ,
           0.86481845, -0.904895  ],
         ...,
         [ 0.06860056, -0.45536193, -1.2713169 , ...,  1.5060574 ,
           1.3941131 , -0.97114813],
         [ 0.14993908, -0.05182786, -1.3196014 , ...,  2.3348632 ,
           1.3805138 , -0.4796164 ],
         [ 0.6433828 , -0.46940032, -1.1205467 , ...,  2.5178921 ,
           0.5583686 , -1.1043622 ]]], dtype=float32)>,
 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 4.78872180e-01, -6.90507233e-01, -6.45176351e-01,
         -1.70674026e-01, -6.60097778e-01,  7.55691051e-01,
          2.83896327e-01,  7.24015772e-01, -6.89178050e-01,
          2.16536373e

In [56]:
input_data = {
    "token_ids": np.ones(shape=(1, 12), dtype="int32"),
    "segment_ids": np.array([[0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0]]),
    "padding_mask": np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

In [57]:
model = AlbertBackbone(
    vocabulary_size=40000,
    num_layers=12,
    num_heads=12,
    num_groups=1,
    num_inner_repetitions=1,
    embedding_dim=128,
    hidden_dim=768,
    intermediate_dim=3072,
    max_sequence_length=12

)

In [58]:
output = model(input_data)

In [59]:
output

{'sequence_output': <tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
 array([[[-0.75534403, -0.75417334,  0.33269697, ..., -1.4872432 ,
          -0.02140048,  0.3107443 ],
         [-0.7471708 , -1.1808239 ,  0.37219864, ..., -1.0479399 ,
           0.20953861,  0.5745775 ],
         [-0.8838515 , -0.8517772 ,  0.8287881 , ..., -1.3643435 ,
          -0.23354311,  0.29294768],
         ...,
         [-1.2791067 , -1.4830219 ,  0.3637959 , ..., -0.80328214,
           0.24591447,  0.17525207],
         [-0.93527675, -1.0091276 ,  0.1830863 , ..., -0.6074742 ,
          -0.31253108,  0.27885374],
         [-0.66678584, -1.4363064 ,  0.46831828, ..., -1.1809998 ,
          -0.37692195,  0.2886842 ]]], dtype=float32)>,
 'pooled_output': <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
 array([[ 3.37796539e-01, -3.70496154e-01,  5.03299654e-01,
          2.66553372e-01, -3.42828691e-01, -1.12798244e-01,
         -4.27170098e-02,  7.26790607e-01, -2.89803326e-01,
          1.64868310e

In [60]:
from keras_nlp.models import AlbertClassifier

In [65]:
features = ["The quick brown fox jumped.", "I forgot my homework."]
labels = [0, 3]

In [66]:
#pretrained classifier
classifier = AlbertClassifier.from_preset("albert_base_en_uncased", num_classes=4,)

/usr/local/lib/python3.10/dist-packages/keras_nlp/src/models/backbone.py:37: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return id(getattr(self, attr)) not in self._functional_layer_ids
/usr/local/lib/python3.10/dist-packages/keras_nlp/src/models/backbone.py:37: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return id(getattr(self, attr)) not in self._functional_layer_ids


In [67]:
classifier.fit(x=features, y=labels, batch_size=2)

1/1 [==============================] - 59s 59s/step - loss: 1.0710 - sparse_categorical_accuracy: 0.5000


In [68]:
classifier.predict(x=features, batch_size=2)

1/1 [==============================] - 12s 12s/step


array([[ 0.36460766, -0.75142205, -0.86742896, -0.08825801],
       [-0.16667296, -0.8212894 , -1.0983584 ,  0.33867338]],
      dtype=float32)